# Generated by Django 5.0.7 on 2024-07-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_category_hotelcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Default City', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Default Country', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.CharField(default='Default State', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
    ]
