# Generated by Django 5.0.7 on 2024-07-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_room_description_remove_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Default First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Default Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.hotelcategory'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Default Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='state',
            field=models.CharField(default='Default State', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.hotel'),
        ),
        migrations.AlterField(
            model_name='roomamenity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.room'),
        ),
    ]
