# Generated by Django 5.0.7 on 2024-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
